"""there were added new model "Reservation"

Revision ID: 12fcb037e135
Revises: 11bb1b724b31
Create Date: 2024-01-20 12:58:15.074574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fcb037e135'
down_revision = '11bb1b724b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
